// import switcher from './switcher';
import './js/themes';
import './js/top-books';
import './js/fetch-categories';
import './js/fireBaseFnunctions.js';
import './js/support';
import './js/render-books-by-category';
import './js/auth/modal-auth/eventsProcessor';
import './js/pop-up-book';
import './js/footer';